-- Migration: Claims module schema expansion
-- Date: 2026-04-12
-- هدف: إضافة دعم قواعد البيانات لوحدة الشكاوى/البلاغات (Claims)

BEGIN;

-- A) Sites reference table
CREATE TABLE IF NOT EXISTS public.sites (
    site_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name character varying(255) NOT NULL UNIQUE,
    site_code character varying(50) UNIQUE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Add site reference to departments (nullable for backward compatibility)
ALTER TABLE public.departments
    ADD COLUMN IF NOT EXISTS site_id integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'departments_site_id_fkey'
    ) THEN
        ALTER TABLE public.departments
            ADD CONSTRAINT departments_site_id_fkey
            FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_departments_site_id ON public.departments(site_id);

-- B) Extend claims table to support UI
ALTER TABLE public.claims
    ADD COLUMN IF NOT EXISTS title character varying(255) NOT NULL DEFAULT 'Untitled',
    ADD COLUMN IF NOT EXISTS priority character varying(20) NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN IF NOT EXISTS assigned_to_user_id integer,
    ADD COLUMN IF NOT EXISTS department_id integer,
    ADD COLUMN IF NOT EXISTS site_id integer,
    ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS closed_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS qualification_notes text;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_assigned_to_user_id_fkey') THEN
        ALTER TABLE public.claims
            ADD CONSTRAINT claims_assigned_to_user_id_fkey
            FOREIGN KEY (assigned_to_user_id) REFERENCES public.users(user_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_department_id_fkey') THEN
        ALTER TABLE public.claims
            ADD CONSTRAINT claims_department_id_fkey
            FOREIGN KEY (department_id) REFERENCES public.departments(department_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_site_id_fkey') THEN
        ALTER TABLE public.claims
            ADD CONSTRAINT claims_site_id_fkey
            FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
            ON DELETE SET NULL;
    END IF;
END $$;

-- Status/Priority integrity (use NOT VALID for safety on existing installations)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_status_chk') THEN
        ALTER TABLE public.claims
            ADD CONSTRAINT claims_status_chk
            CHECK (status IN ('OPEN','QUALIFIED','ASSIGNED','IN_PROGRESS','CLOSED'))
            NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_priority_chk') THEN
        ALTER TABLE public.claims
            ADD CONSTRAINT claims_priority_chk
            CHECK (priority IN ('CRITICAL','HIGH','MEDIUM','LOW'))
            NOT VALID;
    END IF;
END $$;

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_claims_status ON public.claims(status);
CREATE INDEX IF NOT EXISTS idx_claims_priority ON public.claims(priority);
CREATE INDEX IF NOT EXISTS idx_claims_equipment_id ON public.claims(equipment_id);
CREATE INDEX IF NOT EXISTS idx_claims_requester_id ON public.claims(requester_id);
CREATE INDEX IF NOT EXISTS idx_claims_assigned_to_user_id ON public.claims(assigned_to_user_id);
CREATE INDEX IF NOT EXISTS idx_claims_created_at ON public.claims(created_at);
CREATE INDEX IF NOT EXISTS idx_claims_department_id ON public.claims(department_id);
CREATE INDEX IF NOT EXISTS idx_claims_site_id ON public.claims(site_id);

-- C) Upgrade claim_photos to store uploaded file metadata
ALTER TABLE public.claim_photos
    ADD COLUMN IF NOT EXISTS original_name text,
    ADD COLUMN IF NOT EXISTS file_path text,
    ADD COLUMN IF NOT EXISTS content_type character varying(255),
    ADD COLUMN IF NOT EXISTS file_size bigint,
    ADD COLUMN IF NOT EXISTS uploaded_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS uploaded_by character varying(255);

CREATE INDEX IF NOT EXISTS idx_claim_photos_claim_id ON public.claim_photos(claim_id);

-- D) Enrich claim_status_history without breaking existing rows
ALTER TABLE public.claim_status_history
    ADD COLUMN IF NOT EXISTS changed_by character varying(255),
    ADD COLUMN IF NOT EXISTS note text;

CREATE INDEX IF NOT EXISTS idx_claim_status_history_claim_id ON public.claim_status_history(claim_id);
CREATE INDEX IF NOT EXISTS idx_claim_status_history_changed_at ON public.claim_status_history(changed_at);

COMMIT;
